version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hiper-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte123!
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hiper-rabbitmq
    ports:
      - "5672:5672"   # Porta da fila
      - "15672:15672" # Painel administrativo (login: guest/guest)